const products = [
  {
    type: "patty",
    name: "Beef",
    vegetarian: false,
    price: 6.0,
    image:
      "https://www.mychefsapron.com/wp-content/uploads/How-to-make-juicy-burgers.jpg",
  },
  { type: "patty", name: "Brisket", vegetarian: false, price: 6.0, image: "" },
  {
    type: "patty",
    name: "Impossible",
    vegetarian: true,
    price: 6.0,
    image: "",
  },
  { type: "topping", name: "Lettuce", vegetarian: true, price: 0.2, image: "" },
  {
    type: "topping",
    name: "Mushrooms",
    vegetarian: true,
    price: 0.2,
    image: "",
  },
  { type: "topping", name: "Onions", vegetarian: true, price: 0.2, image: "" },
  {
    type: "topping",
    name: "Caramelized Onions",
    vegetarian: true,
    price: 0.2,
    image: "",
  },
  { type: "topping", name: "Pickles", vegetarian: true, price: 0.2, image: "" },
  { type: "topping", name: "Tomato", vegetarian: true, price: 0.2, image: "" },
  {
    type: "topping",
    name: "Jalapenos",
    vegetarian: true,
    price: 0.2,
    image: "",
  },
  { type: "topping", name: "Bacon", vegetarian: false, price: 1.0, image: "" },
  {
    type: "cheese",
    name: "American Cheese",
    vegetarian: true,
    price: 0.8,
    image: "",
  },
  {
    type: "cheese",
    name: "Pepper Jack",
    vegetarian: true,
    price: 0.8,
    image: "",
  },
  { type: "cheese", name: "Swiss", vegetarian: true, price: 0.8, image: "" },
  { type: "sauce", name: "Ketchup", vegetarian: true, price: 0.2, image: "" },
  { type: "sauce", name: "Barbeque", vegetarian: true, price: 0.2, image: "" },
  { type: "sauce", name: "Hot Sauce", vegetarian: true, price: 0.2, image: "" },
  { type: "sauce", name: "A1", vegetarian: true, price: 0.2, image: "" },
];

export { products };
